### ISSUE TITLE
fn_loadoutselect.sqf base class

### ISSUE THREAD

**Issue by Walzmine** [unheilligkeit/TFW_Template#30]
In der fn_loadoutselect.sqf müssen alle Einheiten Basisklassen der Loadouts: B_Helicrew_F nach B_helicrew_F umbenannt werden, da diese sonst nicht erkannt werden. (Ingame wird das H klein geschrieben)

**Comment by TFWIsaac** [comment]
Ist das nur bei der Helicrew so? Es gibt auch andere wo Buchstaben groß geschrieben werden

**Comment by Walzmine** [comment]
Habs nur bei der helicrew festgestellt, ansonsten hat das loadout soweit gegriffen.

**Comment by unheilligkeit** [comment]
https://community.bistudio.com/wiki/Arma_3_CfgVehicles_WEST
ist gefixt obwohl es local anderst heisst muss getestet werden auf dem server
